// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveCommand.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	greenJoystick = new Joystick(1);
	greenJoystick->SetAxisChannel(Joystick::kTwistAxis, 3);	
	yellowJoystick = new Joystick(3);
	
	redJoystick = new Joystick(2);
	
	blueJoystick = new Joystick(4);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Drive Command", new DriveCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getGreenJoystick() {
	return greenJoystick;
}

Joystick* OI::getYellowJoystick() {
	return yellowJoystick;
}
Joystick* OI::getRedJoystick() {
	return redJoystick;
}
Joystick* OI::getBlueJoystick() {
	return blueJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
float OI::GetDriveStickX()
{
	return greenJoystick->GetX();
}
float OI::GetDriveStickY()
{
	return greenJoystick->GetY();
}
float OI::GetDriveRotation()
{
	
	return greenJoystick->GetTwist();
}
float OI::GetArmStickY()
{
	return blueJoystick->GetY();
}
