// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3950.MeShell.subsystems;
import org.usfirst.frc3950.MeShell.RobotMap;
import org.usfirst.frc3950.MeShell.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftFront = RobotMap.drivetrainLeftFront;
    SpeedController leftBack = RobotMap.drivetrainLeftBack;
    SpeedController rightFront = RobotMap.drivetrainRightFront;
    SpeedController rightBack = RobotMap.drivetrainRightBack;
    RobotDrive driveMotors = RobotMap.drivetrainDriveMotors;
    RobotDrive drive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
        public Drivetrain() {
        drive = new RobotDrive(leftFront, leftBack, rightFront, rightBack);
       
    }
    static double leftSped;
    static double rightSped;
    public void tankDrive(double leftSpeed, double rightSpeed) {
//        System.out.println("left: " + leftSpeed + " right: " + rightSpeed);
        drive.tankDrive(-leftSpeed, -rightSpeed);
        leftSped = leftSpeed;
        rightSped = rightSpeed;
    }
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

