// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* greenJoystick;
	JoystickButton* resetGyroButton;
	JoystickButton* launchAngleButton;
	Joystick* yellowJoystick;
	Joystick* redJoystick;
	Joystick* blueJoystick;
	//Joystick* xBox;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* openClawButton;
	JoystickButton* autoLaunchButton;
	JoystickButton* rollBallInButton;
	JoystickButton* rollBallOutButton;
	JoystickButton* resetArmPotOriginButton;
	JoystickButton* gotoLaunchAngle;
	JoystickButton* disableArmPIDMode;
	JoystickButton* FireButton;
	
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getBlueJoystick();
	Joystick* getRedJoystick();
	Joystick* getYellowJoystick();
	Joystick* getGreenJoystick();
	//Joystick* getXBox(); 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	
	//JoystickButton* DPadUp; 
	//JoystickButton* DPadDown;
	float GetDriveStickX();
	float GetDriveStickY();
	float GetDriveRotation();
	float GetArmStickY();
	bool GetTopPositionButton();
	bool GetShootPositionButton();
	bool GetBottomPositionButton();
	float GetArmSpeed();
	bool GetLaunchButton();
	bool GetOpenClawButton();
	bool GetCloseClawButton();
	bool GetRollOutButton();
	bool GetRollInButton();
	
	
};
#endif
