// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "GantrySubsystem.h"
#include "../Logging.h"
#include "../RobotMap.h"
#include "../Commands/CheckContainerAlignmentCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

GantrySubsystem::GantrySubsystem() : Subsystem("GantrySubsystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	liftSolenoid = RobotMap::gantrySubsystemLiftSolenoid;
	leftGripSolenoid = RobotMap::gantrySubsystemLeftGripSolenoid;
	rightGripSolenoid = RobotMap::gantrySubsystemRightGripSolenoid;
	crateAlignedSwich = RobotMap::gantrySubsystemCrateAlignedSwich;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void GantrySubsystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	SetDefaultCommand(new CheckContainerAlignmentCommand());

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
bool GantrySubsystem::CheckContanerAlignedLimitSwitch() {
	uint32_t switchState = crateAlignedSwich->Get();

	// This assumes the limit switch is normally closed
	// and reading non-zero
	// When it reads zero, the switch is open, indicating the limit was hit.
	bool limitHit = (switchState == 0) ? false : true;

	if (limitHit)
	{
		Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kWARNING, "*** Container Aligned Limit Switch Hit ***");
	}

	return limitHit;
}
void GantrySubsystem::FireLiftSolenoid(bool fire) {
	liftSolenoid->Set(fire);
}

