// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3950.MeShell;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;
import edu.wpi.first.wpilibj.smartdashboard.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftFront;
    public static SpeedController drivetrainLeftBack;
    public static SpeedController drivetrainRightFront;
    public static SpeedController drivetrainRightBack;
    public static RobotDrive drivetrainDriveMotors;
    public static SpeedController armsArmsMotor;
    public static SpeedController rollersRollersMotor;
    public static SpeedController shooterWheelsLeftWheel;
    public static SpeedController shooterWheelsRightWheel;
    public static DoubleSolenoid pistonPiston;
    public static Compressor pneumaticsCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftFront = new Victor(1, 1);
	LiveWindow.addActuator("Drivetrain", "Left Front", (Victor) drivetrainLeftFront);
        
        drivetrainLeftBack = new Victor(1, 2);
	LiveWindow.addActuator("Drivetrain", "Left Back", (Victor) drivetrainLeftBack);
        
        drivetrainRightFront = new Victor(1, 3);
	LiveWindow.addActuator("Drivetrain", "Right Front", (Victor) drivetrainRightFront);
        
        drivetrainRightBack = new Victor(1, 4);
	LiveWindow.addActuator("Drivetrain", "Right Back", (Victor) drivetrainRightBack);
        
        drivetrainDriveMotors = new RobotDrive(drivetrainLeftFront, drivetrainLeftBack,
              drivetrainRightFront, drivetrainRightBack);
	
        drivetrainDriveMotors.setSafetyEnabled(false);
        drivetrainDriveMotors.setExpiration(0.1);
        drivetrainDriveMotors.setSensitivity(0.5);
        drivetrainDriveMotors.setMaxOutput(1.0);
        armsArmsMotor = new Victor(1, 5);
	LiveWindow.addActuator("Arms", "Arms Motor", (Victor) armsArmsMotor);
        
        rollersRollersMotor = new Victor(1, 6);
	LiveWindow.addActuator("Rollers", "Rollers Motor", (Victor) rollersRollersMotor);
        
        shooterWheelsLeftWheel = new Victor(1, 7);
	LiveWindow.addActuator("Shooter Wheels", "Left Wheel", (Victor) shooterWheelsLeftWheel);
        
        shooterWheelsRightWheel = new Victor(1, 8);
	LiveWindow.addActuator("Shooter Wheels", "Right Wheel", (Victor) shooterWheelsRightWheel);
        
        pistonPiston = new DoubleSolenoid(1, 1, 2);      
	
        
        pneumaticsCompressor = new Compressor(1, 1, 1, 1);
	
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
