// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef INTAKE_SUBSYSTEM_H
#define INTAKE_SUBSYSTEM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class IntakeSubsystem: public Subsystem {
private:
	
	bool clawIsOpen;
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DoubleSolenoid* clawSolenoid;
	SpeedController* intakeWheels;
	

	IntakeSubsystem();
	void InitDefaultCommand();
	
	void OpenClaw();
	void CloseClaw();
	
	bool IsClawOpen() const {return clawIsOpen;}
	
	void SetIntakeWheelsSpeed(float y);
};

#endif
