// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
DoubleSolenoid* RobotMap::doorControlSubsystemDoorSolenoid = NULL;
DigitalInput* RobotMap::doorControlSubsystemContanterLimitSwich = NULL;
Solenoid* RobotMap::gantrySubsystemLiftSolenoid = NULL;
Solenoid* RobotMap::gantrySubsystemLeftGripSolenoid = NULL;
Solenoid* RobotMap::gantrySubsystemRightGripSolenoid = NULL;
DigitalInput* RobotMap::gantrySubsystemCrateAlignedSwich = NULL;
CANTalon* RobotMap::driveSubsystemCANTalon0 = NULL;
CANTalon* RobotMap::driveSubsystemCANTalon1 = NULL;
CANTalon* RobotMap::driveSubsystemCANTalon2 = NULL;
CANTalon* RobotMap::driveSubsystemCANTalon3 = NULL;
RobotDrive* RobotMap::driveSubsystemRobotDrive = NULL;
Gyro* RobotMap::driveSubsystemGyro1 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

#if 0
	// Not hooked up yet.
	doorControlSubsystemDoorSolenoid = new DoubleSolenoid(0, 3, 4);      
	lw->AddActuator("DoorControlSubsystem", "DoorSolenoid", doorControlSubsystemDoorSolenoid);
	
	// Not sure why there is a limit switch needed here.
	// Not hooked up.
	doorControlSubsystemContanterLimitSwich = new DigitalInput(1);
	lw->AddSensor("DoorControlSubsystem", "ContanterLimitSwich", doorControlSubsystemContanterLimitSwich);
#endif
	
	// Hooked up.
	gantrySubsystemLiftSolenoid = new Solenoid(0, 0);
	lw->AddActuator("GantrySubsystem", "LiftSolenoid", gantrySubsystemLiftSolenoid);
	
	// Not hooked up yet.
	gantrySubsystemLeftGripSolenoid = new Solenoid(0, 1);
	lw->AddActuator("GantrySubsystem", "LeftGripSolenoid", gantrySubsystemLeftGripSolenoid);
	
	// Not hooked up.
	gantrySubsystemRightGripSolenoid = new Solenoid(0, 2);
	lw->AddActuator("GantrySubsystem", "RightGripSolenoid", gantrySubsystemRightGripSolenoid);
	
	// Present and hooked up.
	gantrySubsystemCrateAlignedSwich = new DigitalInput(0);
	lw->AddSensor("GantrySubsystem", "CrateAlignedSwich", gantrySubsystemCrateAlignedSwich);

	
	driveSubsystemCANTalon0 = new CANTalon(0);
	
	
	driveSubsystemCANTalon1 = new CANTalon(1);
	
	
	driveSubsystemCANTalon2 = new CANTalon(2);
	
	
	driveSubsystemCANTalon3 = new CANTalon(3);
	
	
	driveSubsystemRobotDrive = new RobotDrive(driveSubsystemCANTalon0, driveSubsystemCANTalon1,
              driveSubsystemCANTalon2, driveSubsystemCANTalon3);
	
	driveSubsystemRobotDrive->SetSafetyEnabled(true);
        driveSubsystemRobotDrive->SetExpiration(0.1);
        driveSubsystemRobotDrive->SetSensitivity(0.5);
        driveSubsystemRobotDrive->SetMaxOutput(1.0);

	driveSubsystemGyro1 = new Gyro(0);
	lw->AddSensor("DriveSubsystem", "Gyro 1", driveSubsystemGyro1);
	driveSubsystemGyro1->SetSensitivity(0.007);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
