// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3950.Robot2013;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainMotor1;
    public static SpeedController driveTrainMotor2;
    public static SpeedController driveTrainMotor3;
    public static SpeedController driveTrainMotor4;
    public static RobotDrive driveTrainDriveMotors;
    public static DoubleSolenoid driveTrainShifter;
    public static AnalogChannel shooterPotentiometer;
    public static SpeedController shooterSpeedController2;
    public static SpeedController shootershooterwheel1;
    public static RobotDrive shooterShooterWheels;
    public static SpeedController shooterAimer;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainMotor1 = new Victor(1, 1);
	LiveWindow.addActuator("Drive Train", "Motor 1", (Victor) driveTrainMotor1);
        
        driveTrainMotor2 = new Victor(1, 2);
	LiveWindow.addActuator("Drive Train", "Motor 2", (Victor) driveTrainMotor2);
        
        driveTrainMotor3 = new Victor(1, 3);
	LiveWindow.addActuator("Drive Train", "Motor 3", (Victor) driveTrainMotor3);
        
        driveTrainMotor4 = new Victor(1, 4);
	LiveWindow.addActuator("Drive Train", "Motor 4", (Victor) driveTrainMotor4);
        
        driveTrainDriveMotors = new RobotDrive(driveTrainMotor1, driveTrainMotor2,
              driveTrainMotor3, driveTrainMotor4);
	
        driveTrainDriveMotors.setSafetyEnabled(true);
        driveTrainDriveMotors.setExpiration(0.1);
        driveTrainDriveMotors.setSensitivity(0.5);
        driveTrainDriveMotors.setMaxOutput(1.0);
        driveTrainShifter = new DoubleSolenoid(1, 1, 2);      
	
        
        shooterPotentiometer = new AnalogChannel(1, 1);
	LiveWindow.addSensor("Shooter", "Potentiometer", shooterPotentiometer);
        
        shooterSpeedController2 = new Victor(1, 7);
	LiveWindow.addActuator("Shooter", "Speed Controller 2", (Victor) shooterSpeedController2);
        
        shootershooterwheel1 = new Victor(1, 6);
	LiveWindow.addActuator("Shooter", "shooter wheel 1", (Victor) shootershooterwheel1);
        
        shooterShooterWheels = new RobotDrive(shootershooterwheel1, shooterSpeedController2);
	
        shooterShooterWheels.setSafetyEnabled(true);
        shooterShooterWheels.setExpiration(0.1);
        shooterShooterWheels.setSensitivity(0.5);
        shooterShooterWheels.setMaxOutput(1.0);
        
        shooterAimer = new Victor(1, 5);
	LiveWindow.addActuator("Shooter", "Aimer", (Victor) shooterAimer);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
