#include "AutoMoveForward.h"

AutoMoveForward::AutoMoveForward() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveSubsystem);
}
/// edit this to change the time the robot moves forward in autonomous///
static const double DriveTimeInSec = 0.6;
// Called just before this Command runs the first time
void AutoMoveForward::Initialize() {
	SetTimeout(DriveTimeInSec);
}
/// edit this to change the speed at which the robot moves in autonomous, it might need to be negated///
static const float DriveForwardSpeed = -1.0;
// Called repeatedly when this Command is scheduled to run
void AutoMoveForward::Execute() {
	Robot::driveSubsystem->MecanumDrive(0, DriveForwardSpeed, 0);
	
}

// Make this return true when this Command no longer needs to run execute()
bool AutoMoveForward::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void AutoMoveForward::End() {
	Robot::driveSubsystem->MecanumDrive(0, 0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoMoveForward::Interrupted() {
	Robot::driveSubsystem->MecanumDrive(0, 0, 0);
}
