// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveCommand.h"
DriveCommand::DriveCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveSubsystem);
}
// Called just before this Command runs the first time
void DriveCommand::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void DriveCommand::Execute() {
	//printf("DriveCommand::Execute -> Entered.\n");
//	Robot::driveSubsystem->MecanumDrive(Robot::oi->getBlueJoystick());
	//float left = -Robot::oi->getBlueJoystick()->GetY();
	//float right= -Robot::oi->getRedJoystick()->GetY();
	
	//float RedY = -Robot::oi->getRedJoystick()->GetY();
	//float RedX = -Robot::oi->getRedJoystick()->GetX();
	
	Robot::driveSubsystem->MecanumDrive(Robot::oi->GetDriveStickX(),
			                            Robot::oi->GetDriveStickY(),
			                            Robot::oi->GetDriveRotation());
	
}
// Make this return true when this Command no longer needs to run execute()
bool DriveCommand::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void DriveCommand::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveCommand::Interrupted() {
}
