// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <Commands/DropDownCommand.h>
#include "Logging.h"
#include "../ConfigKeys.h"
#include "../Config/ConfigInstanceMgr.h"

const double DownCompletionDelayTimeDefault = 0.200;

static bool configInit = false;
static double downCompletionDelayTime = DownCompletionDelayTimeDefault;


DropDownCommand::DropDownCommand()
	: m_startTime(0.0)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::gantrySubsystem);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	if (!configInit)
	{
		downCompletionDelayTime = ConfigInstanceMgr::getInstance()->getDoubleVal(ConfigKeys::Gantry_DownLiftDelayInSecsConfigKey,
																				 DownCompletionDelayTimeDefault);

		configInit = true;
	}

	SetInterruptible(false);
}

// Called just before this Command runs the first time
void DropDownCommand::Initialize() {
	Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand Initialized()");
}

// Called repeatedly when this Command is scheduled to run
void DropDownCommand::Execute() {

	if (m_startTime <= 0.0)
	{
		Robot::gantrySubsystem->FireLiftSolenoid(false);
		m_startTime = Timer::GetFPGATimestamp();

		Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand::Execute() -> Lift is in dropped position.");
	}
}
// Make this return true when this Command no longer needs to run execute()
bool DropDownCommand::IsFinished() {
	double currTime = Timer::GetFPGATimestamp();

	if ((currTime - m_startTime) >= downCompletionDelayTime)
	{
		m_startTime = 0.0;
		Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand IsFinished() called -> Done.");
		return true;
	}

	Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand IsFinished() called.");

	return false;
}

// Called once after isFinished returns true
void DropDownCommand::End() {
	m_startTime = 0.0;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DropDownCommand::Interrupted() {

}
