// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <Commands/DropDownCommand.h>
#include "Logging.h"

DropDownCommand::DropDownCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::gantrySubsystem);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void DropDownCommand::Initialize() {
	Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand Initialized()");
}

// Called repeatedly when this Command is scheduled to run
void DropDownCommand::Execute() {

	Robot::gantrySubsystem->FireLiftSolenoid(false);
	Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand::Execute() -> Lift is in dropped position.");
}

// Make this return true when this Command no longer needs to run execute()
bool DropDownCommand::IsFinished() {
	Logger::GetInstance()->Log(GantrySubsystemLogId, Logger::kINFO, "DropDownCommand IsFinished() called.");
	return true;
}

// Called once after isFinished returns true
void DropDownCommand::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DropDownCommand::Interrupted() {

}
