// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3950.Robot2013.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3950.Robot2013.Robot;
/**
 *
 */
public class  LoadAngle extends Command {
    private final double LOADING_ANGLE = 16.0;
    
    private double angleVoltage = 0.0;
    
    public LoadAngle() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shootingScrew);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.shootingScrew.setPIDSubsystem(true);
        angleVoltage = Robot.shootingScrew.setInclineAngle(LOADING_ANGLE, false);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (Robot.shootingScrew.hasReachedTargetVoltage(angleVoltage))
        {
            return true;
        }
        
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    
    public boolean isInterruptible() {
        return true;
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        Robot.shootingScrew.setPIDSubsystem(false);
    }
}
