// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3950.Robot2013.commands;
import edu.nshs.frc.robot2013.vision.VisionNetworkTableDefs;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3950.Robot2013.Robot;
/**
 *
 */
public class  MiddleGoalVisionTargeting extends GoalVisionTargetingCommandBase {
    public MiddleGoalVisionTargeting() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        super(VisionNetworkTableDefs.MIDDLE_TARGET);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
}
