// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "CockShooter.h"
#include "../Subsystems/ShooterSubsystem.h"

CockShooter::CockShooter() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterSubsystem);
}

// Called just before this Command runs the first time
void CockShooter::Initialize() {
	
}
static const float PULL_BACK_VOLTAGE = -1.0;
// Called repeatedly when this Command is scheduled to run
void CockShooter::Execute() {
	Robot::shooterSubsystem->SetShooterMotorVoltage(PULL_BACK_VOLTAGE);
}

// Make this return true when this Command no longer needs to run execute()
bool CockShooter::IsFinished() {
	
	return Robot::shooterSubsystem->IsArmed();
}

// Called once after isFinished returns true
void CockShooter::End() {
	Robot::shooterSubsystem->SetShooterMotorVoltage(0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CockShooter::Interrupted() {
	Robot::shooterSubsystem->SetShooterMotorVoltage(0.0);
}
