// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "ShooterSubsystem.h"
#include "../Robotmap.h"
#include "../LoggingComponentDefs.h"
#include "DoubleSolenoid.h"

ShooterSubsystem::ShooterSubsystem() : Subsystem("ShooterSubsystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	upperLimitSwitch = RobotMap::shooterSubsystemUpperLimitSwitch;
	lowerLimitSwitch = RobotMap::shooterSubsystemLowerLimitSwitch;
	shooterMotor = RobotMap::shooterSubsystemShooterMotor;
	triggerSolenoid = RobotMap::shooterSubsystemTriggerSolenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ShooterSubsystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void ShooterSubsystem::SetShooterMotorVoltage(float voltage) {
	if ((voltage > 0.0) && CheckUpperLimitSwitch()) {
		voltage = 0.0;
	}
	else if ((voltage < 0.0) && CheckLowerLimitSwitch()) {
		voltage = 0.0;
	}
	
	Logger::GetInstance()->Log(ShooterSubsystemLogId, Logger::kINFO, "ShooterSubsystem: Setting Shooter Motor Voltage to %f", voltage);

	shooterMotor->Set(voltage);

	Logger::GetInstance()->Log(ShooterSubsystemLogId, 
							   Logger::kINFO, 
							   "ShooterSubsystem: Shooter Motor Voltage = %f", 
							   shooterMotor->Get());
	
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
bool ShooterSubsystem::CheckUpperLimitSwitch()
{
	uint32_t switchState = upperLimitSwitch->Get();
	// This assumes the limit switch is normally closed
	// and reading non-zero
	// When it reads zero, the switch is open, inidicating the limit was hit.
	bool limitHit = (switchState == 0) ? false : true;
	
	if (limitHit)
	{
		Logger::GetInstance()->Log(ShooterSubsystemLogId, Logger::kWARNING, "*** Shooter Upper Limit Switch Hit ***");
	}
	
	return limitHit;
}

bool ShooterSubsystem::CheckLowerLimitSwitch()
{
	uint32_t switchState = lowerLimitSwitch->Get();
	// This assumes the limit switch is normally closed
	// and reading non-zero
	// When it reads zero, the switch is open, inidicating the limit was hit.
	bool limitHit = (switchState == 0) ? false : true;
	
	if (limitHit)
	{
		Logger::GetInstance()->Log(ShooterSubsystemLogId, Logger::kWARNING, "*** Shooter Lower Limit Switch Hit ***");
	}
	
	return limitHit;
}


void ShooterSubsystem::ReleaseTrigger() // this is called to relese the elastics to shoot the ball.
{
	triggerSolenoid->Set(DoubleSolenoid::kReverse);
}
void ShooterSubsystem::SetTrigger() //this is called to ready the trigger to fire agian.
{
	triggerSolenoid->Set(DoubleSolenoid::kForward);
}

